language: python
python: "3.7"
dist: xenial

stages:
  - lint
  - name: release
    if: tag IS present

cache:
  paths:
    - .venv

before_install:
  - export POETRY_VERSION="1.0.10"
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - poetry config virtualenvs.in-project true
  - poetry install -v

jobs:
  include:
    - stage: lint
      script:
        - poetry run make lint
    - stage: release
      script:
        - .bin/check_release $TRAVIS_TAG
        - poetry publish --build
